/**
* ===========================================
* Java Pdf Extraction Decoding Access Library
* ===========================================
*
* Project Info:  http://www.jpedal.org
* (C) Copyright 1997-2008, IDRsolutions and Contributors.
*
* 	This file is part of JPedal
*
    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


*
* ---------------
* General.java
* ---------------
*/

package org.jpedal.objects.acroforms.gui.certificates;

public class General extends javax.swing.JPanel {

    /**
     * Creates new form General
     */
    public General() {
        initComponents();
    }

    public void setValues(String name, String notBefore, String notAfter) {
        // TODO Auto-generated method stub
        issuedToBox.setText(name);
        validFromBox.setText(notBefore);
        validToBox.setText(notAfter);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        validToBox = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        issuedToBox = new javax.swing.JLabel();
        validFromBox = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setText("Valid to:");
        add(jLabel1);
        jLabel1.setBounds(10, 70, 80, 20);
        add(validToBox);
        validToBox.setBounds(80, 70, 310, 20);

        jLabel3.setText("Valid from:");
        add(jLabel3);
        jLabel3.setBounds(10, 40, 80, 20);

        jLabel4.setText("Issued to:");
        add(jLabel4);
        jLabel4.setBounds(10, 10, 80, 20);
        add(issuedToBox);
        issuedToBox.setBounds(80, 10, 310, 20);
        add(validFromBox);
        validFromBox.setBounds(80, 40, 310, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel issuedToBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel validFromBox;
    private javax.swing.JLabel validToBox;
    // End of variables declaration//GEN-END:variables
}
