#! /bin/ksh -p
#
# This searches...  Argument is the database directory

PRG=`whence $0` >/dev/null 2>&1
JH_HOME=`/usr/bin/dirname $PRG`
progname=`/usr/bin/basename $0`

export CLASSPATH; CLASSPATH=${JH_HOME}/lib/jsearch.jar

echo CLASSPATH is ${CLASSPATH}
java com.sun.java.help.search.QueryEngine "$@"
